### ISSUE TITLE
ImportError: No module named main

### ISSUE THREAD

**Issue by zder** [ptrv/gpx2spatialite#24]
Folks,

I am attempting to use gpx2spatialite (0.7.0) on OS X (10.10.3), Python (2.79), setuptools(16.0). I keep getting the following response when I run the gpx2spatialite script,

"File "/usr/local/bin/gpx2spatialite", line 9, in <module>
    load_entry_point('gpx2spatialite==0.7.0', 'console_scripts', 'gpx2spatialite')()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named main"

Any ideas as to why this is happening?

**Comment by ptrv** [comment]
I noticed that the entry point in `setup.py` might be wrong. The strange thing is, that on Linux I never got this error. I tried on Mac an was able to reproduce this issue.

@zder Could you please try to install from the branch https://github.com/ptrv/gpx2spatialite/tree/fix-script-entry-point with

```shell
pip install https://github.com/ptrv/gpx2spatialite/archive/fix-script-entry-point.zip
```

and let me know if it fixes the problem

**Comment by zder** [comment]
@ptrv That seems to have fixed the installation problem. Thank you for your help with this.

**Comment by ptrv** [comment]
@zder Thanks for reporting. I updated the package on PyPi with the fix
