### ISSUE TITLE
Unable to load spatialite sqlite3 extension

### ISSUE THREAD

**Issue by johnjohndoe** [ptrv/gpx2spatialite#25]
I installed [*gpx2spatialite v.0.8.0*](https://github.com/ptrv/gpx2spatialite/releases/tag/v0.8.0) on *Ubuntu 15.10* via *pip* into user scope:

``` bash
$ pip install gpx2spatialite --user
```

To import data I run the following command:

``` bash
$ gpx2spatialite import -d test.sqlite -u TestUser ../testdata
```

This fails with the following **error** message:

> Unable to load spatialite sqlite3 extension

### Problem solving approach

I followed your recommendation on how to satisfy dependencies by [enabling loading extensions for *pysqlite-2.6.3.tar.gz*](https://github.com/ptrv/gpx2spatialite/issues/13#issuecomment-36577053) which I found [described in *.travis.yml*](https://github.com/ptrv/gpx2spatialite/blob/v0.8.0/.travis.yml#L19) as well. One difference from your setup is that I choose to install into **user scope** as in `python setup.py install --user` resp. `pip install . --user`. After this I uninstalled and installed *gpx2spatialite* once again. However, the whole setup has no effect - the error stays.

Can you please tell me where I can investigate further to solve this problem?

**Comment by ptrv** [comment]
After you installed `pysqlite`, can you successfully run this command in the python shell?

```python
from pysqlite2 import dbapi2 as spatialite
hasattr(spatialite.Connection, 'enable_load_extension')
```

Do you have already some other python sqlite libarary on your system, which may interfere with your local install? 
Is your user folder in the path? Can the interpreter find the libraries?

You can see your path with:

```python
import sys
for p in sys.path:
  print(p)
```

**Comment by ptrv** [comment]
Btw, are you using python 2?

**Comment by johnjohndoe** [comment]
Python 2.7.10

**Comment by ptrv** [comment]
The issue here is, that for some reason the extension cannot be loaded even the sqlite3 library supports loading extensions. And in case we have `pyspatialite` installed, it never gets loaded because our sqlite3 library supports loading extensions a we prioritize it in favor of `pyspatialite`.
